#include <stdio.h>
#include <assert.h>
#include <math.h>
#include "../kernel/qcore_metriplectic.h"

int main() {
    SystemState state;
    init_system(&state);

    // Run a single step of the simulation
    solve_step(&state, 0.05f);

    // Verification
    // The power draw should be calculated based on the actual voltage pulse
    // generated by the HAL during the simulation step.
    float actual_v_pulse = state.launder.last_v;
    float expected_power = (actual_v_pulse * actual_v_pulse) / 10.0f;
    float tolerance = 0.0001f;

    float actual_power = state.power_draw;

    printf("Power Draw Test:\n");
    printf("  Actual V_Pulse: %.4f V\n", actual_v_pulse);
    printf("  Expected Power: %.4f W\n", expected_power);
    printf("  Actual Power:   %.4f W\n", actual_power);

    assert(fabs(actual_power - expected_power) < tolerance);

    printf("Test PASSED.\n");

    return 0;
}
